services:
  server:
    container_name: prodServer
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"  # For HTTPS access
      - "5001:5001"  # For HTTP access
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - EVENTLET_NO_GREENDNS=YES
    restart: always
